services:
  mysql:
    image: mysql:8.0
    container_name: axo_nique_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: axo_nique
      MYSQL_USER: axo
      MYSQL_PASSWORD: axo123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: